### ISSUE TITLE
Creating file within a Repo

### ISSUE THREAD

**Issue by dannyti** [CodeHubApp/CodeHub#132]
At present in the iOS Codehub app, we are unable to create a file within a repo. Please provide this option to create a file. 

Thank You.

**Comment by Mortiferr** [comment]
Not sure why this greater would even be desired, that would be a serious pain to type out files on a phone or even tablet.

**Comment by databug** [comment]
@Mortiferr I happen to program everything on my iPad, but I usually use it as a thin client to a Linux VPS for git and compile. I don't have a computer :(

**Comment by asmagill** [comment]
I've done this as well in the past -- a good quality bluetooth keyboard and an iPad can go a long way to not needing to add a computer to your luggage when traveling, so while I don't need this feature right now, I'd definitely consider adding it a plus!

**Comment by Mortiferr** [comment]
@databug Didn't consider that. Good idea, +1

**Comment by jskn** [comment]
Do anyone know any other iOS app where this feature works?

**Comment by Mortiferr** [comment]
@databug My apologies. I hadn't even considered that as an option! My alternative aside from getting this feature added into the app would be getting a cheap chromebook and installing linux.

**Comment by thedillonb** [comment]
The ability to create files has been added to the app in one of the previous releases. If you go to a repository's `Source` there will be a `+` button in the top right which you can use to create files in the current folder.

**Comment by jskn** [comment]
Great! Thanks!
