### ISSUE TITLE
Deviated line numbers when include multi-byte strings

### ISSUE THREAD

**Issue by syuilo** [CodeHubApp/CodeHub#169]
![image](https://cloud.githubusercontent.com/assets/4439005/13843187/861ef6de-ec75-11e5-9c02-7fad97d6c3d9.png)

Sorry my bad English. Thanks!

**Comment by thedillonb** [comment]
Ah, interesting. Good catch. I'll work to fix that in the next release.

**Comment by thedillonb** [comment]
This has been resolved in the current release: 2.16.0
