### ISSUE TITLE
Add Personal Token Login Method

### ISSUE THREAD

**Issue by thedillonb** [CodeHubApp/CodeHub#171]
Allow personal tokens to be used as a login method.

**Comment by mehmetgoksu** [comment]
still waitingg

**Comment by cabarria** [comment]
Bump!

**Comment by schmitzhermes** [comment]
This would be a great thing to have for GHE where you have a company SSO - any updates on this?

**Comment by thedillonb** [comment]
Alright, this has been long waited but next release will have token authentication:

![ezgif-2-041d3f5b8f](https://user-images.githubusercontent.com/1644068/33196265-b7572646-d0ac-11e7-92c3-7b8c6901f386.gif)

**Comment by grammermao** [comment]
mined me




发自网易邮箱大师
On 11/24/2017 13:17, Dillon Buchanan wrote:

Alright, this has been long waited but next release will have token authentication:

**Comment by jberglinds** [comment]
Okay, I got the update and I'm now able to log in to my enterprise account with a token. 
However, no images are loading. Is this a general problem or in some way related to access tokens? Or maybe just my enterprise installation? (using https)
