### ISSUE TITLE
Support for Github's GPG signature verification for commits

### ISSUE THREAD

**Issue by drekryan** [CodeHubApp/CodeHub#187]
I would like to see support for Github's new GPG signature verification feature for commits in CodeHub. Would it be possible to get a verified tag for commits with this signature verification in the app similar to the Github website? I would love to see this feature supported.

More information: https://github.com/blog/2144-gpg-signature-verification

API: https://developer.github.com/v3/repos/commits/ (look for commit signature verification towards the bottom of the page)

**Comment by thedillonb** [comment]
Ahh very interesting! Very cool feature. I can definitely implement this. Consider it done for next release.
