### ISSUE TITLE
customize my own code color style

### ISSUE THREAD

**Issue by PinkD** [CodeHubApp/CodeHub#210]
I hope there is an option to customize my own code color style just like IDEs.

**Comment by thedillonb** [comment]
Consider it done for the next release!

**Comment by smileytechguy** [comment]
@thedillonb dang, thats great!  excited!

**Comment by MaXwellFalstein** [comment]
@thedillond is it possible to extend this with issue #201 by adding an ability to alter every colour in the theme.cs file via settings?

It would be awesome to the able to upload a public or private gist file called theme-mod.cs that could be loaded into the app direct from GitHub to change theme.cs, but not replace theme.cs. That would semi automate the whole process.

I am thinking the main use for theme-mod.cs is for people with three or more iOS devices or for iOS labs at schools, colleges, universities and in the professional sectors.
