### ISSUE TITLE
Allow creating Enterprise accounts with just a token

### ISSUE THREAD

**Issue by docwhat** [CodeHubApp/CodeHub#219]
Some GitHub Enterprise installations have custom SSO solutions.  Instead of trying to support all types of SSO, etc. I propose that CodeHub should take a URL and a token that the user has to create.

This is a little more annoying, but much more flexible.

**Comment by thedillonb** [comment]
Good suggestion. As a ironic cheat, you can actually create a token and use it as your "password" when you create your enterprise account.

**Comment by wuyongjun** [comment]
hh


发自 网易邮箱大师
在2016年08月17日 11:23，Dillon Buchanan 写道:

Good suggestion. As a ironic cheat, you can actually create a token and use it as your "password" when you create your enterprise account.

**Comment by docwhat** [comment]
@thedillonb: That's what I tried to do.  However, the SSO prevented it by trying to redirect to a host that isn't accessible outside our firewall.

**Comment by cabarria** [comment]
I have the same problem. Is there anyway to configure the app to connect to GHE installations using SAML?

**Comment by thedillonb** [comment]
Tracking this under #171.
