### ISSUE TITLE
User profile photo

### ISSUE THREAD

**Issue by ghost** [CodeHubApp/CodeHub#233]
# Why my profile photo dont show in the program?

![Safari](http://i.imgur.com/6rsI8Nk.jpg)

![CodeHub](http://i.imgur.com/gHeQ1zT.jpg)

iPhone 4s.

**Comment by thedillonb** [comment]
I can't explain why your image doesn't load. Even on my device, yours out of all the users I've crossed is the only one that doesn't load. I'll continue to investigate why.

**Comment by MarseilleDev** [comment]
# See, if I change the picture on different picture, it is displayed in the program.

![GitHub](https://cloud.githubusercontent.com/assets/19198757/19410816/cc03c128-92fd-11e6-8d3e-fb005ffc946f.png)

![CodeHub](https://cloud.githubusercontent.com/assets/19198757/19410817/cc0d473e-92fd-11e6-9d91-1e09cc9902e2.png)

**Comment by thedillonb** [comment]
I have yet to be able to reproduce this. If someone else experiences this re-open the issue. However, the only person to ever report this seems to have deleted their account so I'm closing this.
