### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by mikeerickson** [CodeHubApp/CodeHub#248]
Any chance one of the contributors has worked on (or working on) a dark theme for CodeHub?

If not, would such a PR be acceptable?

**Comment by mikeerickson** [comment]
🏓

**Comment by TheRealGus** [comment]
wtf I didn't subscribe to this and even I after I muted this I'm still getting emails about it quite perplexing

**Comment by thedillonb** [comment]
@TheRealGus Simply unwatch the repository. When you downloaded the app, during the walkthrough, you must have tapped "Watch" which would subscribe you for notifications.

**Comment by thedillonb** [comment]
Consolidating issues. Dupe of #127
