### ISSUE TITLE
Cant auth for enterprise

### ISSUE THREAD

**Issue by DemonBob** [CodeHubApp/CodeHub#257]
Hi guys, 

Having trouble authenticating for enterprise. I'm using an oauth token, and my username. When I test with a curl I get valid data back. When trying with codehub it errors out, with you do not have permissions to modify this resource. The oauth token has all admin permissions (infact all are checked).

**Comment by DemonBob** [comment]
So I tried iOctocat and it works fine. I've cloned the CodeHub repo and if I get some downtime I'll try to get it working.

**Comment by thedillonb** [comment]
This should hopefully be resolved in a current release as token authentication is a first-class citizen now.
