### ISSUE TITLE
For loop visual error in C

### ISSUE THREAD

**Issue by massimoG12345** [CodeHubApp/CodeHub#259]
![](http://i.imgur.com/apsjhAD.jpg)
The second and third arguments in a for loop in C are visually shown as comments

**Comment by thedillonb** [comment]
Latest release, 2.16.0, has improved C highlighting. 

<img width="372" alt="screen shot 2017-12-16 at 2 34 29 pm" src="https://user-images.githubusercontent.com/1644068/34073726-4403b5a0-e26e-11e7-9f00-f7fdf9d9100b.png">
