### ISSUE TITLE
Line numbers misaligned when file text is largely a non-Roman script such as Gurmukhi

### ISSUE THREAD

**Issue by DavidHaslam** [CodeHubApp/CodeHub#287]
Text written in a non-Roman script such as **Gurmukhi** (as for the Punjabi language) has diacritics above and below the letter characters.

No allowance is made for how this affects the line spacing in the displayed file text, with the result that the line numbers in the left margin become more and more misaligned further down the file.

I observed this problem while displaying files in the **punjabi_1945_bible** repository.

**Comment by DavidHaslam** [comment]
[Punjabi Pavitr Bible 1945 Edition](https://github.com/tfbf/punjabi_bible_1945)

**Comment by DefaultYuan** [comment]
#>

**Comment by mc-gaolei** [comment]
WTF

**Comment by DavidHaslam** [comment]
![screenshot](http://i.imgur.com/dVyDxp7.jpg)

Captured using CodeHub from iPad Mini viewing one of the source/usfm files in the aforementioned repository.

The issue is clearly illustrated.

Use the Explore feature of CodeHub to find the repository.
The link in my earlier comment goes directly to it in GitHub.
That link was merely to confirm the existence of the repo.
Obviously, as this is a CodeHub issue, it's not visible in GitHub.

**Comment by thedillonb** [comment]
Interesting! Good find. Should be an easy fix for next release.

**Comment by DavidHaslam** [comment]
Off the beaten track for many developers, yet important for the wider world we live in.

**Comment by thedillonb** [comment]
This has been resolved in the current release (2.16.0) as multibyte strings are better supported.
