### ISSUE TITLE
Clicking a push notification goes to wrong list

### ISSUE THREAD

**Issue by jscheel** [CodeHubApp/CodeHub#307]
When I get a push notification on my phone about a github notification, clicking on it should take me to that notification, or to the notifications list. Instead, it takes me to the news page, which does not list the notification.

**Comment by gingerbeardman** [comment]
+1

**Comment by thedillonb** [comment]
Which kind of notifications are you clicking on that don't open up to that page? Perhaps I don't get the notifications you do, but issue notifications that I click on outside of the app open CodeHub right to that view.

**Comment by jscheel** [comment]
@thedillonb the notification I just got for your comment opened to the wrong view when I clicked on it.

**Comment by gingerbeardman** [comment]
Any movement on this. It's my main interaction with the App and it annoys me every time. Help me obi-wan

**Comment by thedillonb** [comment]
Yeah I'm actually in the process of fixing it now. It'll be in the next release.

**Comment by gingerbeardman** [comment]
Great! Thanks

**Comment by gingerbeardman** [comment]
It seems that it works OK if the app has been used recently and is still in memory and you're logged in. 

If the app has to reopen and needs to log you in again then the destination of the push notification is forgotten.

**Comment by gingerbeardman** [comment]
Woohoo! I arrived here from a push notification. 

Thanks
