### ISSUE TITLE
Cant access font-awesome pro private repo

### ISSUE THREAD

**Issue by si458** [CodeHubApp/CodeHub#323]
Hi
I'm not able to see a private repo of another github user even tho i have been given access and its accessible using github.com or desktop app?let when i have signed in
I have paid for the pro version of codehub and shows enabled but still can't find it or see it?
Any ideas?
Simon

**Comment by LordRich** [comment]
Am 24.08.2017 22:12 schrieb "Simon Smith" <notifications@github.com>:

**Comment by si458** [comment]
Blank email? Was the ment to be a message attached to that or do you have the same issue as me?

**Comment by thedillonb** [comment]
Is this repository that you're trying to view part of an organization?

**Comment by si458** [comment]
I think so but not 100% sure? how wud i check?

**Comment by ycrepeau** [comment]
Same problem with the same repo.

The stranger thing is that I receive notification of issues:

![image](https://user-images.githubusercontent.com/6821466/29783963-507f4530-8bf0-11e7-8cb5-4a3fcc1cdaba.png)

If I click on an issue to get more details, I have this error:

![image](https://user-images.githubusercontent.com/6821466/29784050-a324fbea-8bf0-11e7-8844-943b1de7b945.png)

**Comment by ycrepeau** [comment]
FontAwesome is an organization with 4 members.

**Comment by nathane** [comment]
Possible solution.

> If you're a member of an organization and have a third-party application (eg. CodeHub) that you want to use, simply ask your organization's admins to approve access. They can then review the requested application to decide whether it should have access to your organization's data.
https://github.com/blog/1941-organization-approved-applications

![](https://cloud.githubusercontent.com/assets/865/5805312/5701e842-9fd3-11e4-8f7b-a2bad994eb0a.gif)

**Comment by si458** [comment]
![image](https://user-images.githubusercontent.com/765314/30474190-c1c5fabe-99fa-11e7-8281-55790acdafaa.png)
so basically ive gotta sit and wait for fortawesome to approve it? seems abit silly really

**Comment by garrettw** [comment]
@si458 As you can see, your other organizations don't require you to request access. So blame that on FortAwesome, not CodeHub.

**Comment by thedillonb** [comment]
Sorry I'm late to the party on this. @garrettw is right on the money. This is a security precaution the organization has set up. It's out of CodeHub's, or any third-party client for that matter, control until access is granted from the organization. Furthermore, the app can't even see the organization until access is granted so it can't even alert you to the fact you don't have access to it 😭. 

As for @ycrepeau issue about receiving notifications and seeing the repository's issues without actually having been grated access to the organization: I'm pretty sure you just found a GitHub bug. There's no way that you should see those issues if CodeHub has not been granted access. I will follow up with GitHub - perhaps it's a bug in the API. For example, I too belong to the Font Awesome Pro project (but my CodeHub is not granted access), I can see all the issues of the project in CodeHub, but if I go to "Issues" (https://github.com/issues) in my browser I don't see those issues.

I'm going to close this as @si458's original issue is now a waiting game from FontAwesome.
