### ISSUE TITLE
No push notifications

### ISSUE THREAD

**Issue by citrus-it** [CodeHubApp/CodeHub#330]
I bought the pro upgrade and turned on push notifications a while ago but I've never received any and there's nothing showing in the Notifications page on the app.

CodeHub has permissions on my account, including organisation access, and the connection information says it was used in the past week so I must be missing something.

**Comment by thedillonb** [comment]
So you are receiving notifications?

**Comment by citrus-it** [comment]
Sorry, I should have added a comment. I switched to gitter for help rather than an issue. 
Since then I've found comments saying that web notifications need to be enabled and I got a notification about your comment here, so looks like it's working. 

Thanks!
