### ISSUE TITLE
Private organizations are not listed

### ISSUE THREAD

**Issue by kamthamc** [CodeHubApp/CodeHub#336]
I am a paid subscriber and I cannot see the private and public organizations.

**Comment by thedillonb** [comment]
@kamthamc please see https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization. If you can't see your organizations then they have 3rd-party access disabled and you need to request access for the app. CodeHub cannot do this for you - GitHub explicitly designed it to work this way.
