### ISSUE TITLE
Select “master” by default when “viewing source”

### ISSUE THREAD

**Issue by bradgessler** [CodeHubApp/CodeHub#337]
When I view the source code for a repo with 1000’s of branches, I can’t easily scroll to `master` without paging through a bunch of branches.

Consider defaulting to the master branch when I tap on “Source code” and allowing me to change the branch when I’m viewing the source code.

**Comment by garrettw** [comment]
Or at least, always put master at the top of the list.

**Comment by thedillonb** [comment]
This is what I'm putting together right now. What do you think? The `default` branch is always set when viewing the source and you can now change branches/tags on the fly as you navigate.

![kapture 2017-10-11 at 22 01 51](https://user-images.githubusercontent.com/1644068/31475664-1c2e2924-aed0-11e7-985e-43a177a71924.gif)

**Comment by bradgessler** [comment]
Implementation is perfect. It’s exactly what I had in mind when I wrote up the issue. Thanks! 🙏

**Comment by garrettw** [comment]
Semi-related question: why is it that some repos I visit (in the current release) don't even show me a list of branches but rather go straight into a source tree? I haven't figured out the pattern yet with the ones that do and the ones that don't.

**Comment by thedillonb** [comment]
Changes are out in the wild now! Sorry it took a while but the latest version is finally on the App Store.
