### ISSUE TITLE
left arrow icon 

### ISSUE THREAD

**Issue by georgexsh** [CodeHubApp/CodeHub#340]
it seems not properly aligned?

**Comment by georgexsh** [comment]
feedback post directly to github issue..?! cant believe this.

**Comment by thedillonb** [comment]
Haha, what? You can't believe that an open source GitHub app would send issues to the GitHub project page? Where would you rather it go?

**Comment by georgexsh** [comment]
title of the form is "report a bug", no text mentioned github issue.

**Comment by garrettw** [comment]
If it were labeled as a mere feedback form, I could see how you might think that form submission would not be posted publicly. But I think it's perfectly reasonable for something that clearly says "bug report" to be posted publicly if it's an open-source project.

**Comment by georgexsh** [comment]
nevertheless, it is preferable to have hint points out the form was sent as public github issue.
