### ISSUE TITLE
Can’t redeem my PRO account

### ISSUE THREAD

**Issue by NowaHutaGames** [CodeHubApp/CodeHub#341]

**Comment by garrettw** [comment]
Please list the steps you took, where you encountered a problem, and what the exact problem was. No one can help you without more info.

**Comment by thedillonb** [comment]
@NowaHutaGames can you please provide some more information about the trouble you are experiencing?

**Comment by thedillonb** [comment]
Closing as there has been no response.

**Comment by ovo1381** [comment]
oh sorry I see this message right now.. what's the problem??

**Comment by NowaHutaGames** [comment]
It is ok. Thanks
