### ISSUE TITLE
Unable to see organizations on Pro version

### ISSUE THREAD

**Issue by lvolinier** [CodeHubApp/CodeHub#346]
Hi all!

I’ve upgraded to pro version in order to access to some organizations do I belong to but they are not listed.

Could to please help me?

Thanks in advance,
Leo

**Comment by garrettw** [comment]
@lvolinier please see https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization. If you can't see your organizations then they have 3rd-party access disabled and you need to request access for the app. CodeHub cannot do this for you - GitHub explicitly designed it to work this way.

**Comment by LeiBinglin** [comment]
发自我的 iPhone

在 2017年10月26日，00:36，Garrett W. <notifications@github.com<mailto:notifications@github.com>> 写道：


@lvolinier<https://github.com/lvolinier> please see https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization. If you can't see your organizations then they have 3rd-party access disabled and you need to request access for the app. CodeHub cannot do this for you - GitHub explicitly designed it to work this way.

**Comment by thedillonb** [comment]
Thanks @garrettw! @lvolinier all you need should be in that link. If you have any trouble re-open and we can assist you.
