### ISSUE TITLE
Student Mode

### ISSUE THREAD

**Issue by bogga** [CodeHubApp/CodeHub#347]
Hi,

I spend a lot of time away from home and due to the risk of plagiarism I have to make almost all of my repos private, so I was wondering if you could offer a student mode so I could view my private repos on the go?

As a dev I understand this might not be feasible, so don't worry if it's not possible.

Thanks,
Adam

**Comment by thedillonb** [comment]
@bogga shoot me an email (my address is in my GitHub profile) and I'll shoot you a Promo code which should unlock that for you!
