### ISSUE TITLE
Being unable to locate the requested resource

### ISSUE THREAD

**Issue by new-programer** [CodeHubApp/CodeHub#352]
When i click concrete project of the "Resource", it makes an error prompt "the server is unable to locate the requested resource "

**Comment by thedillonb** [comment]
That error would indicate that either the thing you're trying to access does not exit, or, even more likely, that you don't have access to view it. What exactly are you trying to access?

**Comment by thedillonb** [comment]
@new-programer do you have any feedback on what you're trying to access that may help diagnose this issue?

**Comment by thedillonb** [comment]
Closing as there has been no response from the reporter.
