### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by fishme** [CodeHubApp/CodeHub#361]
Can not see any images in readme files.

**Comment by garrettw** [comment]
I can't duplicate this - images are working fine for me. Just tested it on my [Vitals](https://github.com/garrettw/vitals) repository. Do you have the latest version of the app?

**Comment by thedillonb** [comment]
@fishme, do you have an example README that is experiencing these issues?

**Comment by thedillonb** [comment]
Closing this as there is no response - all my testing has indicated that images are working just fine in readme files.
