### ISSUE TITLE
Can't log in to enterprise account that uses SSO

### ISSUE THREAD

**Issue by jberglinds** [CodeHubApp/CodeHub#370]
Hello, I just bought the app for enterprise support but I am unable to log in. 
Is there a way to do it? Maybe using personal access tokens?

**Comment by thedillonb** [comment]
@jberglinds, I'll throw personal access tokens into the next release. Should see it in your hands, hopefully, by the start of next week.

**Comment by thedillonb** [comment]
@jberglinds I'm going to track this under #171. Since that had been created first.
