### ISSUE TITLE
Can't connect to my private account

### ISSUE THREAD

**Issue by piergst** [CodeHubApp/CodeHub#386]
Hi, I just get codehub for companies but I can't connect to my account. I got an error message : Unable to login! Cookies must be enabled to use GitHub (iOs). Could you help me?

**Comment by thedillonb** [comment]
@piergst I saw your image. I am extremely confused as CodeHub doesn't use Cookies to communicate with enterprise instances. I will look into whats happening - I might have to reach out to someone at GitHub for this one.

**Comment by piergst** [comment]
Ok thanks for your support.. Let me know as soon as you have something new.

**Comment by thedillonb** [comment]
Hey @piergst, what is the domain URL that you're using?

**Comment by piergst** [comment]
Hi it is https://github.com/mydomain

**Comment by thedillonb** [comment]
That URL, http://github.com, would seem to suggest that you're actually referring to an organization, not a GitHub Enterprise instance. Try not using the Enterprise login, in CodeHub, but rather, use the normal GitHub.com way.

**Comment by thedillonb** [comment]
@piergst, I'm closing this as I believe your problem lies in the fact your trying to login to an Enterprise account but should have actually been a GitHub.com account - as described above. Re-open this if it's not the case.
