### ISSUE TITLE
Organization does not appear

### ISSUE THREAD

**Issue by cfraizer** [CodeHubApp/CodeHub#390]
I have the Pro upgrade and my GitHub org shows up when I visit my profile from a browser, not not when I select “Profile” in the app.

Suggestions?

**Comment by garrettw** [comment]
This is a common problem that has been addressed many times over in previous issues. (#359, #346, #339, #336 - just to name a few)
Please see https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization. If you can't see your organizations then they have 3rd-party access disabled and you need to request access for the app. CodeHub cannot do this for you - GitHub explicitly designed it to work this way.

**Comment by cfraizer** [comment]
That was indeed the problem. I followed the instructions to which @garrettw linked and the problem is resolved. Thank you!
