### ISSUE TITLE
#-mark in bransch name

### ISSUE THREAD

**Issue by anderscosaq** [CodeHubApp/CodeHub#392]
I can’t access a branch in Github via the CodeHub app when the branch name contains a #-mark. 

It workshop just fine for git and GitHub. 

Example: issue#21

Best regards
Anders

**Comment by anderscosaq** [comment]
The problem is still there. I get the following error message when I try to access branch ”issue#82” in the CodeHub app:

Error
The current directory does not exist under the selected Git reference (issue#82)

mvh
--anders

**Comment by thedillonb** [comment]
Do you already have the new app version: 2.16.0? I just released that to the app store an hour or two ago.

**Comment by anderscosaq** [comment]
Of course. No I don’t. I’ll upgrade and test again. 

Sorry
--anders
