### ISSUE TITLE
Cannot see my private repos

### ISSUE THREAD

**Issue by jiansan** [CodeHubApp/CodeHub#399]
Hi I am the Pro user but I cannot find my private Repo on Github. I can when I visit it from desktop PC.

Thx
Zhengsan
jiansan@hotmail.com

**Comment by garrettw** [comment]
Please go to https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization. If you can't see your organizations then they have 3rd-party access disabled and you need to request access for the app. Unfortunately, CodeHub cannot do this for you - GitHub explicitly designed it to work this way.

**Comment by thedillonb** [comment]
@jiansan, @garrettw is correct. Please follow the instructions in the link he provided - your private repositories are there, it's just you need to manually enabled the app for them to be visible to it.

**Comment by jiansan** [comment]
Thanks for the answer and I think I figure out where is the problem now.
