### ISSUE TITLE
Your app is too 🤬 good for my brain to handle.

### ISSUE THREAD

**Issue by joematthews** [CodeHubApp/CodeHub#402]
**Correct me if I’m wrong and close the ticket — you’re the expert.**

But if I’m right, then this bug may cause serious brain injury...

*In all seriousness, this app is amazing.  I hope you get the positive feedback, encouragement, and extra scratch you deserve for your efforts on this app.  Thank you.*

P.S.  I am now a lifetime follower, watcher, and evangelist 👍 (whether you like it or not 🧐)

**Comment by thedillonb** [comment]
Thanks for the kind words @joematthews!
