### ISSUE TITLE
Contact me link broken and twitter link to page down

### ISSUE THREAD

**Issue by joematthews** [CodeHubApp/CodeHub#403]
# Hallo! #

After purchasing the upgrade for your app, I noticed the email link, ‘contact me’ is broken because it puts a trailing forward slash at the end of the email address in the iOS Mail app which generates the error

Also the the link to
‘http://dillonbuchanan.com/CodeHub/‘ on your twitter page returns a 404 error.

![Image](https://i.imgur.com/tC8ueIN.jpg)!

![Image](https://i.imgur.com/kcxaY3E.jpg)!

![Image](https://i.imgur.com/BIWpwbB.jpg)!

![Image](https://i.imgur.com/KSn1f4B.jpg)!

❤️Joe

**Comment by thedillonb** [comment]
Oh wow. The twitter link is not so surprising since I don't often check it (sadly) but the email link is extremely disappointing on my part. I can't believe I missed that. I'll fix that ASAP. Thanks for pointing this out!

**Comment by joematthews** [comment]
No problem!👍
