### ISSUE TITLE
Doesn’t look like charity will get helped 

### ISSUE THREAD

**Issue by m1ck2** [CodeHubApp/CodeHub#406]
I was really hoping youse where going to help me open old wallets that I accidentally deleted two years ago when I first noticed that the was activity of other people and programs that I hadn’t intiated in all of my devices. Two years later no matter how many times I delete everything youse are still very active through all devices. But now I was actually asking for help to recover correctly and open those wallets if it had of been done by today’s end it would have given me enough time to do a large scale Xmas special help for disadvantaged children with presents and a collection and help service contributing clothing food and bedding to the homeless people. I am lead to believe there was an extremely large amount of money in my wallets which I am not completely sure if true or not but from memory I bought bitcoin in the few cent range and I believe I brought ethereum before it’s official release. So the probability of it being large amount of funds is there. But I don’t understand why youse want to keep dragging it out when you know I am broke and in bad situation and especially af er I had informed your of what my initial intentions are I was anticipating on millions towards children and homeless for Xmas. But that is starting to look like an impossiblity. I think you. Prefer to just annoy me through my devices rather than actually help anyone let alone me. It may just end up another sad Xmas and the strong possibility of a lot. Of people self harming. Did you know suicidee rates are at there extreme highest at Xmas time so those disadvantaged and homeless are very highly at risk then you have the after marth of it ranging from the unfortunate citizens that find them then the police and emergency works doctors nurses paramedics that clean it up then they have to deal with informing and comforting families of there circumstances and the  cycle begins a big broken cog that refuses to stop turning and destroying the pleasures hopes and dreams of many families friends and workers A grime begging to a new year every year wouldn’t it have been nice to have curved that cycle as much as humanly possible. It’s not to late if youse actually want to seriously help but there is very little to no time left to organise it.

**Comment by garrettw** [comment]
This project (CodeHub) has nothing to do with Bitcoin or Ethereum. Please close this issue and avoid posting irrelevant issues in the future.
