### ISSUE TITLE
Issue descriptions not showing up

### ISSUE THREAD

**Issue by garrettw** [CodeHubApp/CodeHub#409]
I’ve been wondering for a bit if this was actually the case, but I just created my own issue and can now verify the problem. The description I wrote doesn’t show up at all, and it’s not just my issue. Every single issue I open up has no description.

![Image](https://i.imgur.com/vD8dW5h.jpg)

**Comment by garrettw** [comment]
Btw, I posted this through the newly revised Feedback & Support area, and I must say it looks much better! Great job.

**Comment by DavidHaslam** [comment]
I was about to report the same issue. 

Codehub displays the first comment and any subsequent comments, but not the issue itself.

Might this be an "off by one" error?

**Comment by DavidHaslam** [comment]
However, it appears to be a **GitHub** issue rather than a **CodeHub** issue!

I'm seeing the same problem with GitHub viewed in Firefox on my PC.

**Comment by garrettw** [comment]
Really?! I haven’t checked GitHub itself yet today.

**Comment by DavidHaslam** [comment]
GitHub now shows the issue description OK. 

CodeHub doesn't.

**Comment by thedillonb** [comment]
Yeah looks like a problem with CodeHub. I seem to have introduced a race condition when displaying the description where a majority of the time the view renders without having finished parsing the markdown :/ I have a fix in place and will release it ASAP.

**Comment by thedillonb** [comment]
This has been resolved in the latest release.

**Comment by thedillonb** [comment]
Hmm, looks like I didn't completely fix that on second thought. I'm still randomly getting it to occur. Reopening.
