### ISSUE TITLE
Cannot turn on push notifications

### ISSUE THREAD

**Issue by standre** [CodeHubApp/CodeHub#419]
When pressing the button on the app‘s settings I get a popup saying ”Error / Unable to register for push notifications. Object reference not set to an instance if an object.”.

**Comment by thedillonb** [comment]
@standre I'll check this out ASAP. Thanks for reporting this.

**Comment by standre** [comment]
It‘s on iPhone 8 with backup from an SE. I may try to reinstall the app.

**Comment by standre** [comment]
Same error after fresh installation.

(With a new issue: account creation with 2fa ends in blank window. Had to restart app, now it’s fine.)

**Comment by thedillonb** [comment]
Interesting. That new issue you mentioned was actually *just* released to the App Store. When you update it will fix that bug.

**Comment by thedillonb** [comment]
Just released a new version to the App Store that has this fix!

**Comment by standre** [comment]
Indeed. Solved now, thanks!
