### ISSUE TITLE
not starting after the update

### ISSUE THREAD

**Issue by charlesrocket** [CodeHubApp/CodeHub#420]
<img src="http://funkyimg.com/i/2ASmj.png"/>

iOS 11.2.1, 6s

**Comment by thedillonb** [comment]
I'm afraid I can't reproduce this - I've deleted and re-downloaded from the store and it starts every time. Perhaps I'm missing something, can you describe what is happening in the picture?

**Comment by charlesrocket** [comment]
@thedillonb starting the app, it goes back to home screen. this is what it looks like when trying to call app back to the screen

**Comment by heruan** [comment]
I can confirm this on iPhone X iOS 11.2.1 and CodeHub 2.17.13: crashing on app start.

**Comment by koutcher** [comment]
Same problem here.

**Comment by heruan** [comment]
Removing and reinstalling the app did the trick: had to sing-in again, restore in-app purchase, but now it's working.

**Comment by thedillonb** [comment]
Hmm, I finally got it to occur. It looks like it occurs once the app is killed and re-opened after the first time...

**Comment by thedillonb** [comment]
Ok, I've come up with a fix and submitted it to Apple for review. Unfortunately, I'm still a little perplexed why it occurs but this fix will resolve it. I've removed the app from sale to prevent others from downloading it or updating it and hitting this bug. I'm pretty embarrassed about this one. I sincerely apologize to those of you who got hit by this. Apple has been pretty quick to review so hopefully you'll have the fix within a day. 😞

**Comment by heruan** [comment]
Thanks for the quick fix!

**Comment by thedillonb** [comment]
It's live! The new version is out on the App Store (2.17.4.2). Thanks for everyone's patience!

**Comment by charlesrocket** [comment]
@thedillonb thanks! swift update!!

**Comment by garrettw** [comment]
I just updated a minute ago and I’m having this issue now. Can’t open the app at all (haven’t tried reinstalling, kinda don’t want to if I can avoid it).
The App Store’s Updates tab says I have 2.17.4 - is it hiding the final dot section of the version number, or is this actually not the latest code?
