### ISSUE TITLE
After the last update is not available in Russia

### ISSUE THREAD

**Issue by maksim77** [CodeHubApp/CodeHub#421]
Yesterday installed the application, almost immediately came an update that can not be installed because it is not available in my country.

**Comment by thedillonb** [comment]
Give it a few minutes and try again. I had to previously remove the app from the store to prevent users from downloading a bad version. I just released a new update and enabled it for all regions - you should be able to install it as soon as it propagates through the App Store.

**Comment by mbhuddleston** [comment]
I cannot figure out How to ask for help on my website.  I cannot get google
ads to work nor the traffic tracker.  Please advise.  Also if there is a
company better than google I’m game.  (Newbie to all things programming)

**Comment by maksim77** [comment]
Thanks!

**Comment by garrettw** [comment]
@mbhuddleston This is certainly not the place for it, as this is the issue tracker for the CodeHub app. If you can't find your answer on Google, try asking StackOverflow or something.

**Comment by thedillonb** [comment]
@maksim77 are you able to install the upgrade today? It should be propagated to the App Store by now.

**Comment by mbhuddleston** [comment]
Ohh I have no idea how i signed up lol.  I read your emails often but I
thought you were all asking for help for your own website or apps.

**Comment by maksim77** [comment]
@thedillonb yes. Everything is ok now. Thanks you again!

**Comment by garrettw** [comment]
@mbhuddleston You are receiving emails from the CodeHub project on Github because you have "watched" the project. If you wish to stop receiving these emails, please go to the project page and unwatch it.
