### ISSUE TITLE
Tecollo

### ISSUE THREAD

**Issue by tecollo** [CodeHubApp/CodeHub#423]
Uygulamanın tam sürümünü satın aldım ve temel olarak harika. > 100 depoda çalışıyorum ve bildirim görünümü harika, ancak etkilenen repo'yu "yeni bir şey" için tamamen özlüyorum.
Pr veya issue'u açtığımda repo hakkında hiçbir bilgi bulunamıyor.
Gördüğüm şeyin kapsamını görmek benim için çok zor.

Bu iyileştirme harika olurdu. Repo adını, bir pr / issue için genel görünümlere veya (belki daha kolay) bildirim listesine ekleyebilir veya ekleyebilirsiniz.

**Comment by thedillonb** [comment]
Putting the translation here for my reference:

> I bought the full version of the app and it's basically great. I am working at> 100 depot and the manifest view is great, but I completely miss the affected repo for "something new".
When I open the Pr or issue, there is no information about the repo.
It's hard for me to see what it's about.
> This improvement would be great. You can add or add the name of the repo to the public view for a pr / issue or (perhaps easier) to the list of notifications.

**Comment by garrettw** [comment]
Duplicate (really, a copy-and-paste) of #422

**Comment by thedillonb** [comment]
@garrettw haha good catch. Closing this as a dupe of #422 then.
