### ISSUE TITLE
No ability to open new issue for private repo

### ISSUE THREAD

**Issue by lelong88** [CodeHubApp/CodeHub#424]
This was the only feature I was paying for and the app doesn’t have. The screenshot on the AppStore suggested that it would. Refund please

**Comment by thedillonb** [comment]
@lelong88, not sure what you're referring to as the app most definitely has the ability to open issues for private repos - i do it daily. Are you hitting some error or something?

**Comment by lelong88** [comment]
Maybe it’s just me not able to find the feature then. Can you please give some instructions?

I’m seeing this screen but the [+] button on the right corner isn’t there. This is a private repo I’m contributing to but don’t own

[Image]
________________________________

**Comment by thedillonb** [comment]
Are you going to the "Issues" from the slide out menu or are you selecting "Issues" after you've selected a repository? "Issues" from the slide out is similar to that of GitHub's "Issues" that's in the top navigation bar: it shows you issues from all repositories aggregated together but it doesn't have the ability create issues from there given that you're looking at all own issues. However, if you go to, say "Starred" repositories, select a repo, then go to "Issues" from that repo's view then you'll find just that repositories issues along with the "+" sign to create new ones for that repo.

**Comment by lelong88** [comment]
Great, thanks Dillon! Please close this as not an issue then.

________________________________
