### ISSUE TITLE
Requesting org third-party access from within app 

### ISSUE THREAD

**Issue by vassudanagunta** [CodeHubApp/CodeHub#436]
Many people are flumoxed when they see "no organisations” on their org list in CodeHub (#399, #395, #390, #359, #346, #339, #336, #300, #296, #239, #345, #134).

I believe the replies that have been given to these are no longer true. 

[Recent reply](https://github.com/CodeHubApp/CodeHub/issues/395#issuecomment-351096569):
> Please look through the closed issues before posting your own to see if your question has already been answered. This is a common problem that has been addressed many times over in previous issues (#359, #346, #339, #336 - just to name a few) -- not to mention the README itself.
>
> Please go to https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization. If you can't see your organizations then they have 3rd-party access disabled and you need to request access for the app. CodeHub cannot do this for you - GitHub explicitly designed it to work this way.

[@thedillonb](https://github.com/CodeHubApp/CodeHub/issues/359#issuecomment-343800145):
> @garrettw is on the money again. Closing as there is nothing further that can be done from CodeHub's side.

**But this is not true any more!**  I just installed [GitHawk](https://github.com/rnystrom/GitHawk) and it automatically showed a list of my organizations when it requested me to authorize the app's access to my GitHub account and let me separately auth third-party access to each one all on the same page.  I did not have to do anything on my own. 

Checkout rnystrom/GitHawk#60. It's always great with open source projects can help each other. Remember to thank them! 😄

**Comment by thedillonb** [comment]
@vassudanagunta very interesting! I will look into this ASAP. If it's possible it would be a huge win. Thanks for bringing this up!!

**Comment by thedillonb** [comment]
So, unless I inadvertently did something in a previous release when I sign in now with a new account that has an organization I already see the "Grant" button:

![img_2737](https://user-images.githubusercontent.com/1644068/36929417-420ea76a-1e5e-11e8-825c-b9b703e4887d.jpg)

@vassudanagunta is this similar to what you saw with GitHawk?

**Comment by vassudanagunta** [comment]
yeah, seems to be good now.
