### ISSUE TITLE
Organization not showing up - yes, for real

### ISSUE THREAD

**Issue by mayou36** [CodeHubApp/CodeHub#438]
Hi, and no, it is not about the 3rd party app restriction, I am fully aware of that.

My public organization [Phynix](https://github.com/Phynix) does not show up under my repositories on my free account on bettercodehub.

Tried:  
* 3rd party app is explicitly granted (also revoked and regranted)
* 3rd party app restriction completely removed.

Any ideas? Do I miss something?
Thanks for your help!

**Comment by garrettw** [comment]
Not sure if that was a typo or not, but [BetterCodeHub](https://github.com/marketplace/better-code-hub) is a completely different thing. This repo is for CodeHub, an iOS app for GitHub.

**Comment by mayou36** [comment]
@garrettw posted in wrong browser tab. Damn! Sorry
