### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Xc2333** [CodeHubApp/CodeHub#442]
Sometimes when i open a project, it's easy to blink.I hope you can solve this bug.😘

**Comment by garrettw** [comment]
What do you mean by "easy to blink"?

**Comment by gpengpeng** [comment]
Me too! yall be the first people I tell fosho! (i notice i like to speak in
an ebonix tone when im feeling confident) lol.

**Comment by Xc2333** [comment]
Believe it or not, it crashed when I'm ready to respond to your comment！I have upgraded to the latest version, im useing the iPhone SE, iOS11.3.2beta.
