### ISSUE TITLE
Too many comments

### ISSUE THREAD

**Issue by deksden** [CodeHubApp/CodeHub#445]
Hi! Some issues have many comments (https://github.com/postmanlabs/postman-app-support/issues/285) and CodeHub does not display them all!

**Comment by deksden** [comment]
![Image](https://i.imgur.com/pY30tuE.jpg)

**Comment by deksden** [comment]
Same thread on github via safari:

![Image](https://i.imgur.com/HFpN9nu.jpg)

**Comment by deksden** [comment]
See the difference on most recent comment?

**Comment by algesten** [comment]
Wonder if this is an API restriction? iOctocat suffers the exact same problem and this is the reason I investigated switching.

I'd totally buy the pro version if it was fixed. But if it's API :/

**Comment by deksden** [comment]
I did not see any API restriction on listing comments: https://developer.github.com/v3/issues/comments/

Instead, i see that by default GitHub API paginate long lists by default 100 items. So, IMHO, this is paginate bug: https://developer.github.com/v3/guides/traversing-with-pagination/

**Comment by garrettw** [comment]
> Imho, whole this is due to https://github.com/thedillonb/GitHubSharp is updated 2 yrs ago, and, maybe, did not use any pagination API for comments on issues

I don't think so. CodeHub is updated much more often than that, and I think he may actually use octokit for CodeHub now.

**Comment by deksden** [comment]
@garrettw : i m not very familiar with C# and that .net stuff, but GitHubSharp is defined together with Oktokit here: https://github.com/CodeHubApp/CodeHub/blob/master/CodeHub.iOS/packages.config

Oktokit did not have IssueCommentsModel class, GitHubSharp have. I did not find where IssueCommentsModel's container is populated with entries (https://github.com/CodeHubApp/CodeHub/blob/master/CodeHub.Core/ViewModels/Issues/IssueViewModel.cs), so i can not check if it is aware of pagination. 

So, this issue can be solved only by person with some knowledge with CodeHub's code base ;)

**Comment by garrettw** [comment]
> So, this issue can be solved only by person with some knowledge with CodeHub's code base ;)

Exactly. Which is why this conversation is pointless until Dillon chimes in. I won't be saying anything else.

**Comment by thedillonb** [comment]
Yeah as @deksden pointed out, the issue, and pull request, comment loaders were using GitHubSharp which I'm actively trying to deprecate throughout the project. It was currently limiting the number comments that were being returned. I've switched it over to use the Octokit package which will alleviate this issue.
