### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by mrcarlosdev** [CodeHubApp/CodeHub#446]
I bought the pro and I can not see the private repositories

**Comment by garrettw** [comment]
Have you followed [the instructions in the readme](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization)?

**Comment by cactus11111** [comment]
I don't know. I am not sure of it. For a new one, everything is...messy?

**Comment by garrettw** [comment]
I was talking to @mrcarlosdev who opened this issue.

**Comment by cactus11111** [comment]
Oh,sorry. Nice day!

**Comment by thedillonb** [comment]
Closing this. As @garrettw pointed out, the solution is in the read me he posted.
