### ISSUE TITLE
Organizations are not showing

### ISSUE THREAD

**Issue by Aahung** [CodeHubApp/CodeHub#448]
It shows nothing in my organization list.

**Comment by Aahung** [comment]
By switching on “list organizations in menu”, it shows, but when it turns off, entering organization shows “there is no organization”

**Comment by thedillonb** [comment]
@Aahung you need to grant CodeHub permission to access the organization. Try these instructions: https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization
