### ISSUE TITLE
Add more git services 

### ISSUE THREAD

**Issue by rluvaton** [CodeHubApp/CodeHub#451]
# Adding More Git Services

This app is awesome, but I feel like if more git services (Like GitLab) was here too it could be much greater!

**Comment by thedillonb** [comment]
Marking as a duplicate of #268. Embedding GitLab functionally alongside GitHub's is a bit of a technical stretch, but forking the app for GitLab is feasible.

**Comment by rluvaton** [comment]
I will try to do it, if its the problem
