### ISSUE TITLE
Cannot work with organizations 

### ISSUE THREAD

**Issue by iamforrest** [CodeHubApp/CodeHub#457]
1. I cannot see my organization from my profile 

2. I cannot see any repositories owned by my organization ( I am admin)

3. I cannot see any repositories forked from my organization.

**Comment by garrettw** [comment]
1. Have you paid for the Pro version?
2. Have you followed [the instructions in the readme](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization)?

**Comment by iamforrest** [comment]
It is ok now, thanks
