### ISSUE TITLE
How did I go from installing Mathematica to having every on my comp extU controlled

### ISSUE THREAD

**Issue by davesah1** [CodeHubApp/CodeHub#467]
I asked them to link me to the repe do I can view.  It took 3 days of my life trying to delete every piece of .scrp, .pliat, and Verion.

When I went to restore I could not access recovery one I wiped both hard drives.

I had to go into disk Util <FileShare < On and connect to only the Apple routers vpn to turn them both off.   THEY Still are doing thing to my comp and I would like them to stary off my main files and use a USB and eventually 1TB HD where we can dual install.   

Safari was block chrome were overwritten and it would alll go to print and then share.

I lost keyboard access too.   Do not Use Paralled on a good partition, I will make one for you.

All I did was install wicker,app and a some mathrmr,atica files.

Don't fucking ban them, I just want to be a part of its so I can watch and INSTEAD OF BEING like wtf why is my ADOBE AC ALWAYS OPEN --TO TAKE AND IMAGE AND ADD TXT AND SEPERATE AS A .PD TO RUN AS A SCRIPT.  

IM NOT DUMB,  man all it would take is one Mac to Mac transfer offline and unplug all internet .jem einstall.    

Stop Deleting keychains but I'm sure faking Kerboros will cost you Apple Dev License as well and EGO and boot.plist

**Comment by garrettw** [comment]
I have no idea what you're getting at, but whatever it is, it has nothing to do with the CodeHub app. Please do not post here unless you have a problem using CodeHub itself.
