### ISSUE TITLE
trending语言筛选

### ISSUE THREAD

**Issue by liuchanghui1987** [CodeHubApp/CodeHub#472]
无法按 语言进行筛选帖子

**Comment by garrettw** [comment]
Translation: cannot filter trending repos by language

**Comment by thedillonb** [comment]
@liuchanghui1987, try clicking the "All Languages" button at the top of the trending view. You can change the language.

**Comment by liuchanghui1987** [comment]
@tredillonb，l did it,but it doesn’t work!

**Comment by Arc676** [comment]
@liuchanghui1987 你是想按照编程语言还是中/英文这些语言筛选？

@thedillonb I can confirm that the language selection dialog at the top of the Trending tab doesn't work. Switching to any language yields the exact same results.

**Comment by thedillonb** [comment]
Ah I see what you mean. All fixed now. Thanks for pointing this out!
