### ISSUE TITLE
Can't remove pinned repository

### ISSUE THREAD

**Issue by davidcaron** [CodeHubApp/CodeHub#477]
Hi, first of all thanks for the app, I really like it.

I have pinned a repository that was later deleted from github. Now the menu button is inaccessible because the main screen can't load. So I can't remove it from my favorites ☹️

**Comment by thedillonb** [comment]
You can always swipe left on the pinned repository in the slide out menu. It should reveal a "delete" button that will remove it.

**Comment by davidcaron** [comment]
Thanks, I didn't see that...
