### ISSUE TITLE
GitLab Support 

### ISSUE THREAD

**Issue by BaileyJM02** [CodeHubApp/CodeHub#481]
I think it would be awesome to add some GitLab support to the app!

**Comment by garrettw** [comment]
As per #179, due to technical differences between the platforms, it's not that simple to just "add support" for GitLab. So we'll call this a duplicate of #268.
In the future, please do a quick search of existing issues before creating a new one.

**Comment by claudiodcrizzi** [comment]
Mute the thread
-- 
Atenciosamente Claudio Donizeti Colsera Rizzi
Obrigado.
