### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by wantotot** [CodeHubApp/CodeHub#483]

**Comment by karomaie** [comment]
### Jumping in

This is my first real attempt to learn about coding. Of course lots of ideas but it is not enough to have ideas, it is putting the tools together to bring something concrete out of those ideas. 

- [ Practice
- [ Practice
- [Practice
- [Practice]



Los Angeles in early Spring

Culver City. Jefferson & Blair Hills
![img_0616](https://user-images.githubusercontent.com/8071494/41495362-3af1ff3a-70da-11e8-9fbc-3c029af55101.jpg)

![img_0615](https://user-images.githubusercontent.com/8071494/41495385-cfd0f30e-70da-11e8-8e17-cec431475611.jpg)

**Comment by HackingNewbie** [comment]
What is this issue and why does it exist

**Comment by city2black** [comment]
Good luck. Welcome to the world of coding bud.
