### ISSUE TITLE
Not existing organization..

### ISSUE THREAD

**Issue by geniyong** [CodeHubApp/CodeHub#484]
I have partcipated in one organization , named tirrilee and this is private organization. And in this tirrilee, ther are some private repositories.
On github website, ther is not problem about accessing this organization.
But on this application, I cant see any organization. Just displayed no organization message.
How can I connect my organization with this app

**Comment by garrettw** [comment]
Read the [README](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization).
