### ISSUE TITLE
Crashed when save img

### ISSUE THREAD

**Issue by Xc2333** [CodeHubApp/CodeHub#489]
The app was crashed when i save a image in someone readme.md.  It crashed every time when i did that.

   The latest version of Codehub app，iOS11.3，iPhone SE

**Comment by rafaelbpa** [comment]
Also happened to me. Same here, iPhone SE, the latest version of CodeHub, but iOS 11.4.1 instead.

Tried to get an error in the code, but after the crash doesn't appear any log error or anything. Any tips on this someone? I do not know if the absence of log error is a fault in mono/xamarin or codehub project.

**Comment by NeoTim** [comment]
good job
