### ISSUE TITLE
Crashes when viewing particular issue

### ISSUE THREAD

**Issue by jmarshall** [CodeHubApp/CodeHub#497]
Visiting issue 516 in GitHub repo arq5x/bedtools2 brings up the usual page with the first comment or two's text as per normal, then the app immediately crashes.

(On an iPhone SE running iOS 10.3.3.)

https://github.com/arq5x/bedtools2/issues/516

**Comment by thedillonb** [comment]
I'm unable to reproduce this with the latest release. Re-open if you're still having trouble.

**Comment by jmarshall** [comment]
Yes, now works for me in 2.19.0 on iOS 10.3.3 (still) too. Thanks!
