### ISSUE TITLE
How to add organizations

### ISSUE THREAD

**Issue by AlexinaO** [CodeHubApp/CodeHub#501]
Hello, I’m new on GitHub and on CodeHub.
In my GitHub account, I’m a part of 3 organizations.
I can’t see them in Code Hub.
I thought I forgot to indicate something when I signed in for the first time in Code Hub. Thus I delete the app and tried to do again the installation. 
Finally, nothing was asked to me about organizations. 
Could you help me to integrate my organizations on Code Hub?
I thank you. 
Have a good day. 
Alexina

**Comment by DavidIsamu** [comment]
Hi Alex, actually I have the same issue as you.
Wish someone can help me also.

**Comment by 0xjojo** [comment]
Hi Alex, Hi David, please go to
https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization
I hope that may help you

**Comment by thedillonb** [comment]
@0xjojo is correct, that link will help. Organizations do not provide access to third party apps by default. You must enable it if you didn't already when you initially authorized CodeHub to access your account.

**Comment by AlexinaO** [comment]
Dean all,
I can’t access to the link and I didn’t find the subject when I searched it by the search menu. 
I read other issues and I understood that I need to have the pro version of Code Hub. Did I understand correctly?
Thanks for your reply.

**Comment by garrettw** [comment]
You only need the Pro version to interact with private repositories. Organizations can be seen with the free version.

I'll copy and paste the text from that link here since you say you can't find it.
> CodeHub can see all organizations _if they are granted access_. GitHub, by default, disables [third-party access](https://help.github.com/articles/about-third-party-application-restrictions/) for new organizations. Because of this, CodeHub has no knowledge that those organizations even exist. GitHub keeps that information from the app. There are several ways to correct this. If you own the organization follow [these instructions](https://help.github.com/articles/enabling-third-party-application-restrictions-for-your-organization/). If you do not own the organization you can request access for CodeHub by following [these instructions](https://help.github.com/articles/requesting-organization-approval-for-third-party-applications/).
