### ISSUE TITLE
User application remove confirm remove 

### ISSUE THREAD

**Issue by shahulhameed0106** [CodeHubApp/CodeHub#506]
Business support stop unsubscribe confirm unsubscribe WiFi network not sharing user nearby please kindly request all application user business developer support cancel confirm cancel remove confirm remove unsubscribe confirm unsubscribe please WiFi network not sharing nearby please help support please sir http:// url Black online please help me sir https:// website update security support please kindly request sir

**Comment by shahulhameed0106** [comment]
Delete confirm delete user application kindly request children application all application delete please remove confirm remove delete immediately remove support sir

**Comment by garrettw** [comment]
All you have to do is "Unwatch" this repo through the CodeHub app or the GitHub website.
