### ISSUE TITLE
App don’t reload list of organizations 

### ISSUE THREAD

**Issue by jordan1997** [CodeHubApp/CodeHub#507]
Steps:
1) Login into iOS app;
2) Open github web page, Create a new organization on GitHub web page, on computer;
3) Open IOS app;

Expect results:
User can see a new organization in the app

Actual result:
User can’t see a new organization

**Comment by garrettw** [comment]
The [README](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization) tells you everything you need to know.

**Comment by garrettw** [comment]
@junyjkjk That wasn't helpful. Please don't spam.

**Comment by jordan1997** [comment]
access restricted, for all of my organization, but I can see only one of them in the app.

**Comment by garrettw** [comment]
Did you follow [these instructions](https://help.github.com/articles/enabling-oauth-app-access-restrictions-for-your-organization/)?
Or what about [these](https://help.github.com/articles/requesting-organization-approval-for-third-party-applications/)?

**Comment by jordan1997** [comment]
Yes, I done all steps from first instruction

**Comment by jordan1997** [comment]
I found a problem. My organization public, but it did not have any public member. I change visibility for my account inside this organization to the public. Add application show this organization for me into my profile, and inside of left menu too.
