### ISSUE TITLE
Unable to See Private Repositories 

### ISSUE THREAD

**Issue by Erickwhite** [CodeHubApp/CodeHub#511]
I purchased the pro version of CodeHub but still cannot see private repositories or organizations

**Comment by garrettw** [comment]
Have you followed the [instructions in the README](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization) about enabling your organizations?

**Comment by thedillonb** [comment]
Closing this as the instructions garrettw listed are the answer to the problem.
