### ISSUE TITLE
cannot browse source code folders with spaces in the name

### ISSUE THREAD

**Issue by ndreca** [CodeHubApp/CodeHub#517]

**Comment by MYCampanula** [comment]
谢谢你@小窝趴在袋子里，我不耻下问了@高舟

**Comment by DavidHaslam** [comment]
See also #567

**Comment by garrettw** [comment]
The reference was already there, above your comment ;)

**Comment by DavidHaslam** [comment]
Not when viewed via CodeHub on my iPhone. 

Only when viewed on GitHub via normal browser.

**Comment by garrettw** [comment]
Sounds like an idea for another feature request..

**Comment by DavidHaslam** [comment]
The latest release fixed the spaces in folder names & filenames issue.
