### ISSUE TITLE
Keep getting emails

### ISSUE THREAD

**Issue by carlojacobs** [CodeHubApp/CodeHub#519]
I keep getting emails of new issues being opened and that sort of stuff. I have to turn them off, but hav not been able to. Can anybody help me?

**Comment by garrettw** [comment]
You probably signed up for those when you first installed CodeHub without realizing it, if you tapped "Watch" when the app suggested that you watch and/or star this repo. To undo that, you just have to visit this repo in the app or in a browser and un-watch it.

**Comment by carlojacobs** [comment]
That fixed it, thx! Great app btw.

**Comment by LeWarEnds** [comment]
Also make sure to unsubscribe from the thread.

**Comment by garrettw** [comment]
Plus you can close this issue since your problem is resolved.

**Comment by carlojacobs** [comment]
How do I close the issue?

**Comment by LeWarEnds** [comment]
Click on the three tabs on the left right corner.
There you will find the issue tab.
There you can close it.

**Comment by 0Idman** [comment]
Deleted
