### ISSUE TITLE
Unable to edit existing file

### ISSUE THREAD

**Issue by tilek** [CodeHubApp/CodeHub#526]
App Store app description lists "edit files and commit them" in the list of features, but this feature seems missing. I could only find how to create a new file.

**Comment by LeWarEnds** [comment]
Can you send me a link of file so that i can have a view?

**Comment by LeWarEnds** [comment]
If there is such a problem it can be a bit of improvement.

**Comment by thedillonb** [comment]
@tilek, if you click "Source" and find a file you want to edit, simply click that file, then up in the top right click the "Action" button and select "Edit". You can then edit the file and re-commit it.

**Comment by DoctorAnthony** [comment]
知道了，能别发了么
    	

    	获取 Outlook for iOS
    
  



On Fri, Feb 22, 2019 at 8:26 PM +0800, "Dillon Buchanan" <notifications@github.com> wrote:












Closed #526.
