### ISSUE TITLE
Upgrade to pro

### ISSUE THREAD

**Issue by ZichengQu** [CodeHubApp/CodeHub#541]
I’ve already upgraded to pro on my iPad, why do I need to spend money upgrading to pro on my iPhone again with one account?

**Comment by thedillonb** [comment]
@ZichengQu, if the iTunes account is the same then you do not need to purchase it again. In fact, even if you tried to purchase it again it would just enable it on your other device without asking you to pay.

**Comment by DavidHaslam** [comment]
Close this?

**Comment by thedillonb** [comment]
Closing as the original issue seems solved. The garbage characters are covered in another issue already.
