### ISSUE TITLE
Pro version does not list all organizations

### ISSUE THREAD

**Issue by tortinator** [CodeHubApp/CodeHub#544]
My pro version only lists the single public organization
But not the ones with secret repositories.
I’m on an iPad Pro and use the latest version.
Thanks for your support, -ts

**Comment by tortinator** [comment]
Thanks! Will do.

**Comment by thedillonb** [comment]
Closing this. @tortinator let me know if you're still unable to see your organizations after granting them `Third-party access`. We can take another look if that is the case.
