### ISSUE TITLE
About README

### ISSUE THREAD

**Issue by yocaning** [CodeHubApp/CodeHub#547]
The link in codeHub  #README does not take effect

**Comment by martinpeck** [comment]
At the top of the README.md there's an image, with a hyperlink. It's that one. Everything else in that README.md appears to be ok.

i.e. this...

https://github.com/CodeHubApp/CodeHub/blame/master/README.md#L1


```
<a href="http://thedillonb.github.io/CodeHub/"><img alt="CodeHub" src="https://raw.githubusercontent.com/thedillonb/CodeHub/gh-pages/assets/CodeHubTitle.jpg" width="100%"></a>
```
