### ISSUE TITLE
No organisations shown 

### ISSUE THREAD

**Issue by miking7** [CodeHubApp/CodeHub#550]
I paid for the pro upgrade to be able to use with private repos of the two organisations I administer... but codehub does not show these organisations or their private repos. Help please.

**Comment by garrettw** [comment]
Have you followed [the instructions in the README](https://github.com/CodeHubApp/CodeHub/blob/master/README.md#i-cant-find-my-repository)?

**Comment by thedillonb** [comment]
Closing as following the instructions that @garrettw mentioned will resolve the issue for you.
