### ISSUE TITLE
cannot access private repositories which uses SSO auth.

### ISSUE THREAD

**Issue by yagitatsu** [CodeHubApp/CodeHub#561]
I Upgraded CodeHub app to pro, but I cannot access private repositories which uses SSO auth.

**Comment by garrettw** [comment]
Have you followed [the instructions in the README](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-repository)?

**Comment by yagitatsu** [comment]
No, thanks ! I understood I have to request access of organization owner 😃

**Comment by MYCampanula** [comment]
啦啦啦啦啦啦啦

**Comment by MYCampanula** [comment]
党参加一
