### ISSUE TITLE
Add project name in push notification 

### ISSUE THREAD

**Issue by iShankarG** [CodeHubApp/CodeHub#562]
![Image](https://i.imgur.com/SdRynvl.jpg)

Currently the push notification shows `<someone> released <version>`, but if includes project name it’s more helpfull.

**Comment by LeWarEnds** [comment]
Yeah it would be helpful.

**Comment by sirisak1985** [comment]
yes i want to be usrful

**Comment by deathdogg** [comment]
I agree

**Comment by iShankarG** [comment]
Best format might be `<package> <version> released`
