### ISSUE TITLE
Getting notifications for projects I’m not following 

### ISSUE THREAD

**Issue by questsin** [CodeHubApp/CodeHub#565]
Just started to pay via iOS. Getting notifications for projects I’m not following

**Comment by sirisak1985** [comment]
issue

**Comment by sirisak1985** [comment]
issue

**Comment by timtjtim** [comment]
Sirisak,

Please stop replying “issue” to all reported bugs. It’s incredibly annoying, and it is unhelpful.

Thanks.

**Comment by questsin** [comment]
looks like I was following a repo. my bad
