### ISSUE TITLE
Cannot access folders in any source

### ISSUE THREAD

**Issue by DavidHaslam** [CodeHubApp/CodeHub#567]
![Image](https://i.imgur.com/o83q4xc.jpg)

The error popup occurs with any folder in any repository that has a folder.

**Comment by thedillonb** [comment]
@DavidHaslam do you have a `master` branch? Is that a public repository?

**Comment by DavidHaslam** [comment]
Yes - one master branch. 

Repository is new today. 

https://github.com/DavidHaslam/From-Death-Into-Life

It’s public. 

I even posted the link on my Facebook wall.

**Comment by thedillonb** [comment]
Ah, you're hitting #517. I actually just fixed that last night. I'm putting together a release as soon as possible and will have that fix. I'm going to close this and track the bug at #517

**Comment by DavidHaslam** [comment]
Thanks.

_Comforting to know it was not just me that had the problem._

**Comment by DavidHaslam** [comment]
Thanks for the fix. 

It works.
