### ISSUE TITLE
codehub is a Oauth app or github app?

### ISSUE THREAD

**Issue by bupojung** [CodeHubApp/CodeHub#575]
codehub is a Oauth app or github app?

**Comment by bupojung** [comment]
fsfsd

**Comment by huangxionging** [comment]
艹尼玛




在2019年03月18日 09:51，bupo 写道：

fsfsd

**Comment by Jeremy-JM** [comment]
建议你删掉你的评论~ @huangxionging

**Comment by wwx0306** [comment]
因为你我都决定取消订阅了，你还是可以的，自己玩吧

发自我的 iPhone
