### ISSUE TITLE
Access to Private repositories stopped working

### ISSUE THREAD

**Issue by mareklab** [CodeHubApp/CodeHub#576]
As above, I lost access to private repositories my company has granted me access to. It all works fine when logging in via github.com website, but no longer via this app. Yes, I have purchased Pro version.

**Comment by mareklab** [comment]
Also I cannot see anything under Organisations

**Comment by miking7** [comment]
Same problem here.

**Comment by garrettw** [comment]
Have you followed the [instructions in the README](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization)?

**Comment by miking7** [comment]
Thanks @garrettw. The bit about "I can't find my organisation" was the key to get it working for me.
