### ISSUE TITLE
how to run this project using xamain?

### ISSUE THREAD

**Issue by bupojung** [CodeHubApp/CodeHub#577]
I open the CodeHub.iOS.csproj using xamain. and it can  not run because of errors like this:
`/Users/bupozhuang/Desktop/Git/CodeHub/CodeHub.iOS/CSC: Error CS0006: Metadata file '/Users/bupozhuang/Desktop/Git/CodeHub/CodeHub.Core/bin/iPhone/Debug/CodeHub.Core.dll' could not be found (CS0006) (CodeHub.iOS)
/Users/bupozhuang/Desktop/Git/CodeHub/CodeHub.iOS/CSC: Error CS0006: Metadata file '/Users/bupozhuang/Desktop/Git/CodeHub/CodeHub/bin/Debug/CodeHub.dll' could not be found (CS0006) (CodeHub.iOS)`

**Comment by thedillonb** [comment]
Even on another computer I can't reproduce this issue.
