### ISSUE TITLE
FEATURE REQUEST: Project View and Markdown checkboxes

### ISSUE THREAD

**Issue by melMass** [CodeHubApp/CodeHub#580]
Thanks for this app.
I'm relying quite a lot on GitHub projects and would like to know if there is plans for it ?

**Comment by rayray87** [comment]
Thanks for the mail.

I have to admit that I’m not sure.

**Comment by garrettw** [comment]
Follow #228 for updates on that.

**Comment by rayray87** [comment]
Thanks Garrett

**Comment by melMass** [comment]
Thanks, I'll close in favour of #228
