### ISSUE TITLE
GitHub classroom repositories do not appear

### ISSUE THREAD

**Issue by wesamjabali** [CodeHubApp/CodeHub#581]
I purchased pro as a means to have access to my github classroom projects on mobile, but only my personal ones are appearing.

**Comment by wesamjabali** [comment]
I have purchased the extended version of course. My school does not have an enterprise network, they just use github classroom and it’s hooked up to my own personal account.

**Comment by garrettw** [comment]
Have you followed the [instructions](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization) in the README?

**Comment by wesamjabali** [comment]
I see, I need to request access from my teacher. Oh well, thank you for the response.
