### ISSUE TITLE
Repo cannot loaded after I upgraded 

### ISSUE THREAD

**Issue by Hearen** [CodeHubApp/CodeHub#583]

**Comment by garrettw** [comment]
Have you followed the [instructions](https://github.com/CodeHubApp/CodeHub#i-cant-find-my-organization) in the README?

**Comment by rayray87** [comment]
I haven't

**Comment by rayray87** [comment]
I haven't. Should I get in there?

**Comment by garrettw** [comment]
No, it's not.

**Comment by Hearen** [comment]
Thank you so much for the so effective reply. I downloaded, checked the features and then I upgraded before which I can check my repos after I upgraded, I cannot and after many killing and restarting, now it seems working. Thank you for the response;) professional team




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            hearen
                            
                            
                                
                                    邮箱：lhearen@126.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 04/10/2019 23:01, Garrett W. wrote: No, it's not.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CodeHubApp/CodeHub","title":"CodeHubApp/CodeHub","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CodeHubApp/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@garrettw in #583: No, it's not."}],"action":{"name":"View Issue","url":"https://github.com/CodeHubApp/CodeHub/issues/583#issuecomment-481726814"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CodeHubApp/CodeHub/issues/583#issuecomment-481726814",
"url": "https://github.com/CodeHubApp/CodeHub/issues/583#issuecomment-481726814",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
