### ISSUE TITLE
Suggestions for my site 

### ISSUE THREAD

**Issue by FarisFaleh** [CodeHubApp/CodeHub#589]
I hope you are doing well 
Please check my account and site 
Let me know if there’s any suggestions or comments

**Comment by garrettw** [comment]
This area is only for issues and support related to the CodeHub app.

**Comment by JGShew** [comment]
Go away you bozo

**Comment by garrettw** [comment]
@JGShew That kind of message will not be tolerated here. If you don't want to get blocked from the repo you might want to delete that comment before Dillon sees it.
