### ISSUE TITLE
trending not working!

### ISSUE THREAD

**Issue by lanxuexing** [CodeHubApp/CodeHub#599]

**Comment by 974N** [comment]
Trending is not working for me as well. Tried to select All Languages, Daily, Monthly, weekly but totally not responding.

**Comment by thedillonb** [comment]
Hmm, i suspect this is due to the fact GitHub changed their HTML layout and the crawler can no longer pick up the important elements. Should be an easy backend fix. Thanks for reporting this.

**Comment by k4ch0** [comment]
Same error here!

**Comment by kevcomparadise** [comment]
+ 1

**Comment by JuzouSatoru2** [comment]
Me too

**Comment by tangkv** [comment]
same issue on my side, waiting for the fix and release...

**Comment by adamwulf** [comment]
Not sure what changed, but it’s working for me now. Thanks for the great app!

**Comment by tangkv** [comment]
seems github trending changes a bit on their own side, CodeHub now sees daily/weekly/monthly trending correctly.

**Comment by k4ch0** [comment]
It is working now! Thank you!!

**Comment by thedillonb** [comment]
Should be all set. I updated the backend to accommodate the changes that were made on GitHub.com/trending
