### ISSUE TITLE
Unable to scroll in .md files

### ISSUE THREAD

**Issue by shreyas1599** [CodeHubApp/CodeHub#613]
Scrolling is unresponsive in .md files. 
Device: iPhone 7 iOS 12.4

**Comment by magnoliaceiling** [comment]
This bug is still present in iOS 13.

**Comment by muneirjama** [comment]
So haw would fix the bug? May be it has a compatibility issue so it needs new patches

**Comment by jamesleesaunders** [comment]
Is there any update on this? Unable to scroll markdown files.

**Comment by philipjin** [comment]
still have this issue on ios13

**Comment by remorse85** [comment]
Wie bitte was?

**Comment by steakknife** [comment]
I'm having problems editing markdown where a bullet gets inserted in an existing document, but then the rest of the text is appended to EOF. Also, the scrolling jumps to the bottom momentarily and periodically.

**Comment by garrettw** [comment]
Being that yours is an editing problem rather than a reading problem, would you mind putting that in a new issue?

**Comment by enadol** [comment]
Issue still present on iOS 13.3

**Comment by Bleeck** [comment]
This seems to just be an input issue. I can't scroll by swiping but I did manage to get the page to scroll up or down by doing multiple taps at the bottom of the page or the top of the page respectively.

So just tap like crazy and it should move.

This workaround should keep us going until a proper fix is implemented.

**Comment by firsthubgit** [comment]
iPados  how to fix it

**Comment by cadkins052** [comment]
Scenario!:)

**Comment by techbecca** [comment]
I also have this problem. iOS 13

**Comment by k4ch0** [comment]
Same problem here!

**Comment by guoruibiao** [comment]
so many feedbacks for this question.

**Comment by jpinkham** [comment]
**Easiest workaround**: tap the share icon in the upper right and select “Show in GitHub”. The current markdown page you’re trying to view opens in the app’s embedded web browser. Bonus: you can use “Reader View” of that browser to hide all distracting parts of the page, if you don’t need them


> So just tap like crazy and it should move.

I verified that a double-tap at bottom or top (below the page title) of the screen will get the markdown page to move 1-screenful at a time. With no scrollbar, you can never tell for sure when you’ve reached the bottom.
Caveat: you can’t select any text on the page, but links to other pages work.


> This workaround should keep us going until a proper fix is implemented.

It’s been months and months with this issue outstanding. 😢 Are there any iOS devs out there who could Contribute a fix? I have no iOS experience nor proper dev env.

**Comment by Faroop** [comment]
i have the same problem on my end? anyone know the solution to this?

**Comment by bibstha** [comment]
Fix in #664

**Comment by jpinkham** [comment]
I can confirm that the scrolling issue is now resolved! Download the latest version from the App Store (v2.19.1) which was released about a week ago.
