### ISSUE TITLE
ARIMA not able to find a suitable model

### ISSUE THREAD

**Issue by ps1608** [CodeHubApp/CodeHub#614]
I have 145 weeks of data for multiple center-meal combination. Some center-meal combination may not have all weeks data. plus there are other predictors like base_price,checkout_price,featured_pages etc .
I am trying to build a arima with regression model to forecast num_orders for week 146-154, in a loop for each (center-meal combination and for the combination "55-2139" where center_id=55 and meal_id=2139, I get error "No suitable ARIMA model found"

Data for 55-2139 , is attached

Code:
weekorder=subset(train,train$cMID=="55-2139")
xregtrain=cbind(weekorder$checkout_price,weekorder$base_price,weekorder$emailer_for_promotion,weekorder$homepage_featured)

AutoArimaRegModel=auto.arima(weekorder$num_orders,xreg=xregtrain)
--> I get the error "ARIMA could not find a suitable model"
[data.xlsx](https://github.com/CodeHubApp/CodeHub/files/3517300/data.xlsx)

Please help

**Comment by garrettw** [comment]
@ps1608 Please do not post unrelated/spam messages here.
