### ISSUE TITLE
Organization unavailable

### ISSUE THREAD

**Issue by qongfu-ceo** [CodeHubApp/CodeHub#619]
I am unable to add my organization or delete my account.

**Comment by thedillonb** [comment]
Are you asking for features? Currently you cannot add a new organization or delete your GitHub account from the app. If you want to create a new organization or delete your account you must do it via GitHub.

**Comment by jolt2017** [comment]
so I just want to know how to cancel the email notification for its boring.

**Comment by Frank-Dz** [comment]
thx！




| |
sdudzy
|
|
邮箱：sdudzy@163.com
|

Signature is customized by Netease Mail Master

On 10/11/2019 15:10, jolt2017 wrote:

so I just want to know how to cancel the email notification for its boring.

**Comment by PieroMondora** [comment]
it doesn't seem possible to unsubscribe!

**Comment by Frank-Dz** [comment]
Actually I do not know what is the problem with the subscribe




| |
sdudzy
|
|
邮箱：sdudzy@163.com
|

Signature is customized by Netease Mail Master

On 10/11/2019 17:06, PieroMondora wrote:

it doesn't seem possible to unsubscribe!

**Comment by garrettw** [comment]
You have to go to this repo ("CodeHub") in the app or on desktop and click Unwatch.
