### ISSUE TITLE
Private repo images

### ISSUE THREAD

**Issue by mbcolbert** [CodeHubApp/CodeHub#630]
The paid version allows access to private repos, but you can’t add a photo to an issue in a private repo unless you agree to have it publicly posted to imgur.  This does not meet my expectations and I would not have purchased this app had this detail been disclosed in advance.

![Image](https://i.imgur.com/dmUtmzH.jpg)

**Comment by thedillonb** [comment]
@mbcolbert sorry you found it disappointing. You're welcome to ask for a refund via the iTunes store. GitHub's image upload service is not a public API so the app must seek to host images elsewhere.

**Comment by 519118819** [comment]
Ok
