### ISSUE TITLE
Unable scroll while reading readme.md

### ISSUE THREAD

**Issue by themikesam** [CodeHubApp/CodeHub#636]
As title.

**Comment by garrettw** [comment]
Please check for existing issues that match your problem before posting a new one.

This is a duplicate of #632.

**Comment by azfarB** [comment]
Hello Garett,

Not that I’m saying I haven’t made a problem but can you pls possibly send me a post of the problem in question?

Thanks,
Azfar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by garrettw** [comment]
@azfarB I was not addressing you at all. I was replying to someone else's issue report. If you want to stop receiving these notifications you need to unwatch the CodeHub repository, either through the app or on github.com .

**Comment by azfarB** [comment]
Dear Garett,

I am sorry, I am new to this; so got a little confused. Pls do forgive me!

Best,
Azfar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thedillonb** [comment]
Duplicate of #613.
