### ISSUE TITLE
Can’t see organizations

### ISSUE THREAD

**Issue by stradiot** [CodeHubApp/CodeHub#646]
Application is not listing organizations I belong to. Neither in the sidebar, nor in profile. Updating the list by swiping down does not help.

**Comment by garrettw** [comment]
Have you followed [the instructions in the README?](https://github.com/CodeHubApp/CodeHub#troubleshooting)

**Comment by stradiot** [comment]
Sorry, my bad. After obtaining permission I can see my organization.
