### ISSUE TITLE
error CS0029: Cannot implicitly convert type 'string' to 'int'

### ISSUE THREAD

**Issue by kippenlars** [CodeHubApp/CodeHub#648]
problem with code plz help.
public int height;

  height = character.position.y.ToString("0");

**Comment by garrettw** [comment]
First, it looks like your code is passing a string to a function that expects an int.

Secondly, is this part of CodeHub's source, or something else?
This area is only for reporting issues with using or developing CodeHub itself.

**Comment by msbbk110** [comment]
Sorry for that
I deleted the account from the app
Is that best way to silent my profile
