### ISSUE TITLE
OSError: [Errno 121] Remote I/O error with ADS1115 

### ISSUE THREAD

**Issue by sspikky** [CodeHubApp/CodeHub#655]
I have problem with ADS1115  on raspberry pi 4 model b

![image](https://user-images.githubusercontent.com/61461385/75249834-9a021880-5809-11ea-9109-bfe169ad43d1.png)

and I try another command sudo i2cdetect -y 1

![image](https://user-images.githubusercontent.com/61461385/75249940-d33a8880-5809-11ea-890a-cd0d0f0d8150.png)

it's not show any value 

Could anybody can help me to fix these problems ? T___T

**Comment by cadkins052** [comment]
Scarieo!:)

**Comment by sspikky** [comment]
I can solve the problem because of the slack jumper ....
