### ISSUE TITLE
iPhone SE iOS 13 not scrolling 

### ISSUE THREAD

**Issue by feilipu** [CodeHubApp/CodeHub#658]
No scrolling on readme or on code. This is a regression.

**Comment by garrettw** [comment]
Duplicate of #613

**Comment by guoruibiao** [comment]
so many duplicated issues.

**Comment by Rexogamer** [comment]
This app hasn’t really been worked on much lately. If anyone has made an active fork lmk

**Comment by chris18890** [comment]
Dunno how useful/relevant this is - https://www.itpro.co.uk/software/development/355030/github-releases-mobile-app-for-ios-and-android

**Comment by Rexogamer** [comment]
The official github app is nice but doesn’t have editing support so :/

**Comment by feilipu** [comment]
Closing this. Moving to another application.

Thanks for the initial work.
