### ISSUE TITLE
implement Drap and Drop

### ISSUE THREAD

**Issue by tioannidis** [CodeHubApp/CodeHub#662]
Drag and Drop between apps

**Comment by Bradaitken1983** [comment]
Delete please

**Comment by tioannidis** [comment]
@Bradaitken1983 why?

**Comment by garrettw** [comment]
@tioannidis just ignore that user, they are confused.

**Comment by Bradaitken1983** [comment]
As this account is fake and used to code and script another persons iPhone and applications police and Apple are involved

**Comment by cppguru** [comment]
Get lost
