### ISSUE TITLE
Alomaisi 

### ISSUE THREAD

**Issue by walli55** [CodeHubApp/CodeHub#706]

**Comment by TheTechRobo** [comment]
What is this issue for?

**Comment by TheTechRobo** [comment]
Huh?

**Comment by xuwgCoder** [comment]
unsubscribe On 03/08/2021 09:03, Walli55 wrote: Closed #706. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by walli55** [comment]
> 

keyboards/aleblazer/zodiark/info.json

**Comment by TheTechRobo** [comment]
What is this? I'm not following.
