### ISSUE TITLE
Enable IOS URL-SCHEME for app, to allow for automation and integration into other applications

### ISSUE THREAD

**Issue by demonbob** [CodeHubApp/CodeHub#96]
I propose enabling IOS URL-SCHEME (codehub://) in code hub. This will allow for certain actions to be possible via URL-Scheme. We could then (theoretically) use apps like Launch center pro to create shortcuts to creating new issues for specific repo. 

Senerio 1: In a meeting, a new issue is brought up about one of the projects I own. I would be able to click a shortcut in launch center pro that takes me to that particular repos create issue screen. This could be extended for a lot of code hubs functions.

Senecio 2: I use pythonista for quick IOS automation scripts. I could run a quick script that would query a service like trello that looks for any new cards that have been created on the project board. The script could then use the URL-SCHEME create the issues with codehub to match the cards identifier.

**Comment by maique** [comment]
Is there a way to save a file as .md ? At the moment the file is saved as .txt, and you can change that when CodeHub is getting ready to save the file. Is there a way to force saving it as markdown ?

**Comment by fqure** [comment]
Having CH X-Callback for example in Drafts to create a GitHub issue would help in productivity. Maybe a feature for the pro version
